CFG_SECTION_GENERIC   = 'generic'
CFG_LANGUAGE          = 'language'
CFG_GEOMETRY          = 'geometry'
CFG_START_WITH_SERVER = 'startserver'

CFG_SECTION_SERVER = 'server'
CFG_PORT           = 'port'
CFG_HOST           = 'host'
CFG_THREADS        = 'threads'

CFG_SECTION_LILYPOND      = 'lilypond'
CFG_TEMPLATE              = 'lilypondtemplate'
CFG_COMMAND               = 'lilypondcommand'
CFG_WORKDIR               = 'workdir'
CFG_CACHEDIR              = 'cachedir'
CFG_KEEPLY                = 'keeply'
CFG_DEFAULTHYPHENLANGUAGE = 'defaulthyphenlanguage'
CFG_CUSTOMHYPHENFOLDER    = 'customhyphenfolder'

GUI_GENERIC_SETTINGS  = 'gGenericSettings'
GUI_SERVER_SETTINGS   = 'gServerSettings'
GUI_LILYPOND_SETTINGS = 'gLilypondSettings'
GUI_START_SERVER      = 'gStartServer'
GUI_STARTED_SERVER    = 'gStartedServer'
GUI_STOP_SERVER       = 'gStopServer'
GUI_STOPED_SERVER     = 'gStopedServer'
GUI_SAVE_CONFIG       = 'gSaveConfig'

TXT_DOCUMENTATION        = 'txtDoc'
TXT_DESCRIPTION          = 'txtDescription'
TXT_LOADEDHYPHENS        = 'txtLoadedHyphens'
TXT_CHORUS               = 'txtChorus'
TXT_PRESENTATION_STARTED = 'Presentation started'
TXT_PRESENTATION_STOPPED = 'Presentation stopped'

ERR_INNITHYPHENS    = 'errInitHyphens'
ERR_LOADHYPHENS     = 'errLoadHyphtens'
ERR_HYPHENSNOTFOUND = 'errHyphensNotFound'
ERR_LILYPOND_FAILED = 'errLilypondFailed'
ERR_STARTFAILED     = 'errStartFailed'
